# mybatis-plus 的配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.exam.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: LCH
    password: lch1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 发送邮件配置
  mail:
    host: smtp.qq.com
    username: 1789412739@qq.com
    password: gvoxtuuykrebbgfa
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
#配置文件上传信息
#文件服务本地rest请求对外地址
file:
  staticAccessPath: /upload/**
  uploadFolder: D:/image/
  upload:
    nama: http://127.0.0.1:8888
# 在控制 台上 打印显示sql 语句
#logging.level.com.company.cache:debug
logging:
  level:
    com:
      exam:
        mapper: debug
